"""initial schema

Revision ID: 001_initial_schema
Revises: 
Create Date: 2026-07-26 00:49:27.077766
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '001_initial_schema'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_username'), ['username'], unique=True)

    op.create_table('pet_visual_identities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=False),
    sa.Column('identity_version', sa.String(length=32), nullable=False),
    sa.Column('hair_style', sa.String(length=64), nullable=False),
    sa.Column('eye_style', sa.String(length=64), nullable=False),
    sa.Column('color_palette_json', sa.Text(), nullable=False),
    sa.Column('features_json', sa.Text(), nullable=False),
    sa.Column('reference_images_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'identity_version', name='uq_pet_visual_identity_version')
    )
    with op.batch_alter_table('pet_visual_identities', schema=None) as batch_op:
        batch_op.create_index('ix_pet_visual_identities_template', ['template_id', 'identity_version'], unique=False)

    op.create_table('account_blocks',
    sa.Column('blocker_account_id', sa.String(length=36), nullable=False),
    sa.Column('blocked_account_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blocked_account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blocker_account_id', 'blocked_account_id')
    )
    with op.batch_alter_table('account_blocks', schema=None) as batch_op:
        batch_op.create_index('ix_account_blocks_blocked', ['blocked_account_id'], unique=False)

    op.create_table('admin_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_account_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_admin_audit_resource', ['resource_type', 'resource_id', 'created_at'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('direct_key', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('created_by_account_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('direct_key', name='uq_conversation_direct_key')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index('ix_conversations_updated', ['updated_at'], unique=False)

    op.create_table('friend_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sender_account_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_account_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recipient_account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('friend_requests', schema=None) as batch_op:
        batch_op.create_index('ix_friend_requests_recipient_status', ['recipient_account_id', 'status', 'created_at'], unique=False)
        batch_op.create_index('ix_friend_requests_sender_status', ['sender_account_id', 'status', 'created_at'], unique=False)

    op.create_table('friendships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_low_id', sa.String(length=36), nullable=False),
    sa.Column('account_high_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_high_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['account_low_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_low_id', 'account_high_id', name='uq_friendship_pair')
    )
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.create_index('ix_friendships_high', ['account_high_id', 'created_at'], unique=False)
        batch_op.create_index('ix_friendships_low', ['account_low_id', 'created_at'], unique=False)

    op.create_table('pet_asset_rights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('rights_type', sa.String(length=64), nullable=False),
    sa.Column('source_declaration', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('declared_by_account_id', sa.String(length=36), nullable=False),
    sa.Column('verified_by_account_id', sa.String(length=36), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['declared_by_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verified_by_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pet_asset_rights', schema=None) as batch_op:
        batch_op.create_index('ix_pet_asset_rights_artifact', ['artifact_id'], unique=False)
        batch_op.create_index('ix_pet_asset_rights_status', ['status'], unique=False)

    op.create_table('pet_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_code', sa.String(length=160), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('species', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by_account_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_code')
    )
    with op.batch_alter_table('pet_templates', schema=None) as batch_op:
        batch_op.create_index('ix_pet_templates_status', ['status', 'created_at'], unique=False)

    op.create_table('pets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('template_id', sa.String(length=160), nullable=False),
    sa.Column('template_version', sa.String(length=32), nullable=False),
    sa.Column('identity_version', sa.String(length=32), nullable=False),
    sa.Column('primary_owner_account_id', sa.String(length=36), nullable=False),
    sa.Column('growth_stage', sa.String(length=32), nullable=False),
    sa.Column('growth_level', sa.Integer(), nullable=False),
    sa.Column('growth_exp', sa.Integer(), nullable=False),
    sa.Column('bond_level', sa.Integer(), nullable=False),
    sa.Column('bond_exp', sa.Integer(), nullable=False),
    sa.Column('hunger', sa.Integer(), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('mood', sa.Integer(), nullable=False),
    sa.Column('cleanliness', sa.Integer(), nullable=False),
    sa.Column('health', sa.Integer(), nullable=False),
    sa.Column('boredom', sa.Integer(), nullable=False),
    sa.Column('presence', sa.String(length=32), nullable=False),
    sa.Column('personality_type', sa.String(length=64), nullable=False),
    sa.Column('asset_version', sa.String(length=32), nullable=False),
    sa.Column('state_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['primary_owner_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.create_index('ix_pets_owner', ['primary_owner_account_id'], unique=False)

    op.create_table('reminder_occurrences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_reminder_id', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snooze_count', sa.Integer(), nullable=False),
    sa.Column('last_delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'source', 'source_reminder_id', name='uq_reminder_occurrence_source')
    )
    with op.batch_alter_table('reminder_occurrences', schema=None) as batch_op:
        batch_op.create_index('ix_reminder_occurrences_due', ['account_id', 'state', 'scheduled_at'], unique=False)
        batch_op.create_index('ix_reminder_occurrences_updated', ['account_id', 'updated_at'], unique=False)

    op.create_table('account_pet_relations',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('affinity', sa.Integer(), nullable=False),
    sa.Column('care_contribution', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', 'pet_id')
    )
    op.create_table('account_web_preferences',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('selected_pet_id', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_pet_id'], ['pets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('caregiver_invitations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('invited_account_id', sa.String(length=36), nullable=False),
    sa.Column('invited_by_account_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invited_account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by_account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('caregiver_invitations', schema=None) as batch_op:
        batch_op.create_index('ix_caregiver_invites_pet', ['pet_id', 'status', 'created_at'], unique=False)
        batch_op.create_index('ix_caregiver_invites_recipient', ['invited_account_id', 'status', 'created_at'], unique=False)

    op.create_table('conversation_members',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('last_read_sequence', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', 'account_id')
    )
    with op.batch_alter_table('conversation_members', schema=None) as batch_op:
        batch_op.create_index('ix_conversation_members_account', ['account_id', 'conversation_id'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('public_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('credential_version', sa.Integer(), nullable=False),
    sa.Column('active_pet_id', sa.String(length=36), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['active_pet_id'], ['pets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'public_id', name='uq_device_account_public')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index('ix_devices_account', ['account_id', 'revoked_at'], unique=False)

    op.create_table('messages',
    sa.Column('sequence', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('sender_account_id', sa.String(length=36), nullable=False),
    sa.Column('sender_pet_id', sa.String(length=36), nullable=True),
    sa.Column('message_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sender_pet_id'], ['pets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('sequence'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_conversation_sequence', ['conversation_id', 'sequence'], unique=False)
        batch_op.create_index('ix_messages_sender_created', ['sender_account_id', 'created_at'], unique=False)

    op.create_table('pet_growth_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('from_stage', sa.String(length=32), nullable=False),
    sa.Column('to_stage', sa.String(length=32), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pet_growth_logs', schema=None) as batch_op:
        batch_op.create_index('ix_pet_growth_logs_pet', ['pet_id', 'created_at'], unique=False)

    op.create_table('pet_interaction_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('action_name', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pet_interaction_logs', schema=None) as batch_op:
        batch_op.create_index('ix_pet_interaction_logs_pet', ['pet_id', 'created_at'], unique=False)

    op.create_table('pet_personality_scores',
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('lively_score', sa.Integer(), nullable=False),
    sa.Column('gentle_score', sa.Integer(), nullable=False),
    sa.Column('social_score', sa.Integer(), nullable=False),
    sa.Column('exploratory_score', sa.Integer(), nullable=False),
    sa.Column('lazy_score', sa.Integer(), nullable=False),
    sa.Column('primary_personality', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pet_id')
    )
    op.create_table('pet_privacy',
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('visibility', sa.String(length=24), nullable=False),
    sa.Column('allow_remote_care', sa.Boolean(), nullable=False),
    sa.Column('updated_by_account_id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('pet_id')
    )
    op.create_table('pet_template_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('template_version', sa.String(length=32), nullable=False),
    sa.Column('identity_version', sa.String(length=32), nullable=False),
    sa.Column('asset_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('manifest_json', sa.Text(), nullable=True),
    sa.Column('package_sha256', sa.String(length=64), nullable=True),
    sa.Column('package_size', sa.Integer(), nullable=True),
    sa.Column('staging_object_key', sa.String(length=255), nullable=True),
    sa.Column('created_by_account_id', sa.String(length=36), nullable=False),
    sa.Column('reviewed_by_account_id', sa.String(length=36), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['pet_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'template_version', 'identity_version', 'asset_version', name='uq_pet_template_version_identity')
    )
    with op.batch_alter_table('pet_template_versions', schema=None) as batch_op:
        batch_op.create_index('ix_pet_template_versions_template_status', ['template_id', 'status'], unique=False)

    op.create_table('pet_visits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('requester_account_id', sa.String(length=36), nullable=False),
    sa.Column('host_account_id', sa.String(length=36), nullable=False),
    sa.Column('visitor_pet_id', sa.String(length=36), nullable=False),
    sa.Column('host_pet_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('completion_reason', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['host_account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visitor_pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pet_visits', schema=None) as batch_op:
        batch_op.create_index('ix_pet_visits_host_status', ['host_account_id', 'status', 'created_at'], unique=False)
        batch_op.create_index('ix_pet_visits_requester_status', ['requester_account_id', 'status', 'created_at'], unique=False)
        batch_op.create_index('ix_pet_visits_visitor_pet_status', ['visitor_pet_id', 'status', 'scheduled_end_at'], unique=False)

    op.create_table('user_pet_asset_submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('style_preference', sa.String(length=32), nullable=False),
    sa.Column('personality_hint', sa.String(length=240), nullable=False),
    sa.Column('rights_basis', sa.String(length=32), nullable=False),
    sa.Column('rights_confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('image_media_type', sa.String(length=64), nullable=False),
    sa.Column('image_object_key', sa.String(length=255), nullable=False),
    sa.Column('image_sha256', sa.String(length=64), nullable=False),
    sa.Column('image_size', sa.Integer(), nullable=False),
    sa.Column('image_width', sa.Integer(), nullable=False),
    sa.Column('image_height', sa.Integer(), nullable=False),
    sa.Column('review_comment', sa.Text(), nullable=False),
    sa.Column('reviewed_by_account_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_object_key')
    )
    with op.batch_alter_table('user_pet_asset_submissions', schema=None) as batch_op:
        batch_op.create_index('ix_user_pet_asset_submissions_account_status', ['account_id', 'status', 'created_at'], unique=False)
        batch_op.create_index('ix_user_pet_asset_submissions_hash', ['account_id', 'pet_id', 'image_sha256'], unique=False)
        batch_op.create_index('ix_user_pet_asset_submissions_pet_status', ['pet_id', 'status', 'created_at'], unique=False)

    op.create_table('message_receipts',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'account_id')
    )
    with op.batch_alter_table('message_receipts', schema=None) as batch_op:
        batch_op.create_index('ix_message_receipts_account_state', ['account_id', 'state'], unique=False)

    op.create_table('pet_asset_production_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assignee_account_id', sa.String(length=36), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('status_note', sa.Text(), nullable=False),
    sa.Column('target_template_version_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assignee_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['user_pet_asset_submissions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_template_version_id'], ['pet_template_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', name='uq_pet_asset_production_job_submission')
    )
    with op.batch_alter_table('pet_asset_production_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_pet_asset_production_jobs_account_status', ['account_id', 'status', 'created_at'], unique=False)
        batch_op.create_index('ix_pet_asset_production_jobs_assignee_status', ['assignee_account_id', 'status', 'updated_at'], unique=False)
        batch_op.create_index('ix_pet_asset_production_jobs_pet', ['pet_id', 'created_at'], unique=False)

    op.create_table('pet_asset_releases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_version_id', sa.String(length=36), nullable=False),
    sa.Column('template_code', sa.String(length=160), nullable=False),
    sa.Column('template_version', sa.String(length=32), nullable=False),
    sa.Column('identity_version', sa.String(length=32), nullable=False),
    sa.Column('asset_version', sa.String(length=32), nullable=False),
    sa.Column('object_key', sa.String(length=255), nullable=False),
    sa.Column('package_sha256', sa.String(length=64), nullable=False),
    sa.Column('package_size', sa.Integer(), nullable=False),
    sa.Column('manifest_json', sa.Text(), nullable=False),
    sa.Column('published_by_account_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['published_by_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_version_id'], ['pet_template_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key'),
    sa.UniqueConstraint('template_version_id', name='uq_asset_release_template_version')
    )
    with op.batch_alter_table('pet_asset_releases', schema=None) as batch_op:
        batch_op.create_index('ix_asset_releases_lookup', ['template_code', 'identity_version', 'asset_version'], unique=False)

    op.create_table('sync_events',
    sa.Column('sequence', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('target_device_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sequence'),
    sa.UniqueConstraint('account_id', 'idempotency_key', name='uq_sync_event_account_idempotency'),
    sa.UniqueConstraint('event_id')
    )
    with op.batch_alter_table('sync_events', schema=None) as batch_op:
        batch_op.create_index('ix_sync_events_account_sequence', ['account_id', 'sequence'], unique=False)

    op.create_table('pet_asset_deployments',
    sa.Column('template_code', sa.String(length=160), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('active_release_id', sa.String(length=36), nullable=False),
    sa.Column('previous_release_id', sa.String(length=36), nullable=True),
    sa.Column('updated_by_account_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['active_release_id'], ['pet_asset_releases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['previous_release_id'], ['pet_asset_releases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('template_code', 'channel')
    )
    with op.batch_alter_table('pet_asset_deployments', schema=None) as batch_op:
        batch_op.create_index('ix_pet_asset_deployments_release', ['active_release_id'], unique=False)

    op.create_table('pet_asset_production_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('submission_id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('template_version_id', sa.String(length=36), nullable=False),
    sa.Column('object_key', sa.String(length=255), nullable=False),
    sa.Column('package_sha256', sa.String(length=64), nullable=False),
    sa.Column('package_size', sa.Integer(), nullable=False),
    sa.Column('manifest_json', sa.Text(), nullable=False),
    sa.Column('uploaded_by_account_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['pet_asset_production_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id'], ['user_pet_asset_submissions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_version_id'], ['pet_template_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', name='uq_pet_asset_production_artifact_job'),
    sa.UniqueConstraint('object_key')
    )
    with op.batch_alter_table('pet_asset_production_artifacts', schema=None) as batch_op:
        batch_op.create_index('ix_pet_asset_production_artifacts_submission', ['submission_id', 'created_at'], unique=False)
        batch_op.create_index('ix_pet_asset_production_artifacts_template_version', ['template_version_id'], unique=False)

    op.create_table('pet_asset_production_job_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('actor_account_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['pet_asset_production_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pet_asset_production_job_logs', schema=None) as batch_op:
        batch_op.create_index('ix_pet_asset_production_job_logs_job', ['job_id', 'created_at'], unique=False)

    op.create_table('pet_asset_production_reference_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('image_media_type', sa.String(length=64), nullable=False),
    sa.Column('image_object_key', sa.String(length=255), nullable=False),
    sa.Column('image_sha256', sa.String(length=64), nullable=False),
    sa.Column('image_size', sa.Integer(), nullable=False),
    sa.Column('image_width', sa.Integer(), nullable=False),
    sa.Column('image_height', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=240), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['pet_asset_production_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_object_key')
    )
    with op.batch_alter_table('pet_asset_production_reference_images', schema=None) as batch_op:
        batch_op.create_index('ix_pet_asset_production_refs_hash', ['job_id', 'image_sha256'], unique=False)
        batch_op.create_index('ix_pet_asset_production_refs_job', ['job_id', 'created_at'], unique=False)

    op.create_table('pet_asset_deployment_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('submitted_by_account_id', sa.String(length=36), nullable=False),
    sa.Column('reviewed_by_account_id', sa.String(length=36), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=False),
    sa.Column('rights_verified', sa.Boolean(), nullable=False),
    sa.Column('visual_identity_verified', sa.Boolean(), nullable=False),
    sa.Column('compatibility_json', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['pet_asset_production_artifacts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['pet_asset_production_jobs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submitted_by_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id', name='uq_pet_asset_deployment_review_artifact')
    )
    with op.batch_alter_table('pet_asset_deployment_reviews', schema=None) as batch_op:
        batch_op.create_index('ix_pet_asset_deployment_reviews_pet', ['pet_id', 'created_at'], unique=False)
        batch_op.create_index('ix_pet_asset_deployment_reviews_status', ['status', 'created_at'], unique=False)

    op.create_table('pet_personal_asset_releases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('review_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('template_version_id', sa.String(length=36), nullable=False),
    sa.Column('object_key', sa.String(length=255), nullable=False),
    sa.Column('package_sha256', sa.String(length=64), nullable=False),
    sa.Column('package_size', sa.Integer(), nullable=False),
    sa.Column('manifest_json', sa.Text(), nullable=False),
    sa.Column('published_by_account_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['pet_asset_production_artifacts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['published_by_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['review_id'], ['pet_asset_deployment_reviews.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_version_id'], ['pet_template_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_id', name='uq_pet_personal_asset_release_artifact'),
    sa.UniqueConstraint('object_key'),
    sa.UniqueConstraint('review_id', name='uq_pet_personal_asset_release_review')
    )
    with op.batch_alter_table('pet_personal_asset_releases', schema=None) as batch_op:
        batch_op.create_index('ix_pet_personal_asset_releases_pet', ['pet_id', 'created_at'], unique=False)

    op.create_table('pet_personal_asset_deployments',
    sa.Column('pet_id', sa.String(length=36), nullable=False),
    sa.Column('active_release_id', sa.String(length=36), nullable=False),
    sa.Column('previous_release_id', sa.String(length=36), nullable=True),
    sa.Column('updated_by_account_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['active_release_id'], ['pet_personal_asset_releases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_release_id'], ['pet_personal_asset_releases.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('pet_id')
    )
    with op.batch_alter_table('pet_personal_asset_deployments', schema=None) as batch_op:
        batch_op.create_index('ix_pet_personal_asset_deployments_active', ['active_release_id'], unique=False)
        batch_op.create_index('ix_pet_personal_asset_deployments_previous', ['previous_release_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_personal_asset_deployments', schema=None) as batch_op:
        batch_op.drop_index('ix_pet_personal_asset_deployments_previous')
        batch_op.drop_index('ix_pet_personal_asset_deployments_active')

    op.drop_table('pet_personal_asset_deployments')
    with op.batch_alter_table('pet_personal_asset_releases', schema=None) as batch_op:
        batch_op.drop_index('ix_pet_personal_asset_releases_pet')

    op.drop_table('pet_personal_asset_releases')
    with op.batch_alter_table('pet_asset_deployment_reviews', schema=None) as batch_op:
        batch_op.drop_index('ix_pet_asset_deployment_reviews_status')
        batch_op.drop_index('ix_pet_asset_deployment_reviews_pet')

    op.drop_table('pet_asset_deployment_reviews')
    with op.batch_alter_table('pet_asset_production_reference_images', schema=None) as batch_op:
        batch_op.drop_index('ix_pet_asset_production_refs_job')
        batch_op.drop_index('ix_pet_asset_production_refs_hash')

    op.drop_table('pet_asset_production_reference_images')
    with op.batch_alter_table('pet_asset_production_job_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_pet_asset_production_job_logs_job')

    op.drop_table('pet_asset_production_job_logs')
    with op.batch_alter_table('pet_asset_production_artifacts', schema=None) as batch_op:
        batch_op.drop_index('ix_pet_asset_production_artifacts_template_version')
        batch_op.drop_index('ix_pet_asset_production_artifacts_submission')

    op.drop_table('pet_asset_production_artifacts')
    with op.batch_alter_table('pet_asset_deployments', schema=None) as batch_op:
        batch_op.drop_index('ix_pet_asset_deployments_release')

    op.drop_table('pet_asset_deployments')
    with op.batch_alter_table('sync_events', schema=None) as batch_op:
        batch_op.drop_index('ix_sync_events_account_sequence')

    op.drop_table('sync_events')
    with op.batch_alter_table('pet_asset_releases', schema=None) as batch_op:
        batch_op.drop_index('ix_asset_releases_lookup')

    op.drop_table('pet_asset_releases')
    with op.batch_alter_table('pet_asset_production_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_pet_asset_production_jobs_pet')
        batch_op.drop_index('ix_pet_asset_production_jobs_assignee_status')
        batch_op.drop_index('ix_pet_asset_production_jobs_account_status')

    op.drop_table('pet_asset_production_jobs')
    with op.batch_alter_table('message_receipts', schema=None) as batch_op:
        batch_op.drop_index('ix_message_receipts_account_state')

    op.drop_table('message_receipts')
    with op.batch_alter_table('user_pet_asset_submissions', schema=None) as batch_op:
        batch_op.drop_index('ix_user_pet_asset_submissions_pet_status')
        batch_op.drop_index('ix_user_pet_asset_submissions_hash')
        batch_op.drop_index('ix_user_pet_asset_submissions_account_status')

    op.drop_table('user_pet_asset_submissions')
    with op.batch_alter_table('pet_visits', schema=None) as batch_op:
        batch_op.drop_index('ix_pet_visits_visitor_pet_status')
        batch_op.drop_index('ix_pet_visits_requester_status')
        batch_op.drop_index('ix_pet_visits_host_status')

    op.drop_table('pet_visits')
    with op.batch_alter_table('pet_template_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_pet_template_versions_template_status')

    op.drop_table('pet_template_versions')
    op.drop_table('pet_privacy')
    op.drop_table('pet_personality_scores')
    with op.batch_alter_table('pet_interaction_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_pet_interaction_logs_pet')

    op.drop_table('pet_interaction_logs')
    with op.batch_alter_table('pet_growth_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_pet_growth_logs_pet')

    op.drop_table('pet_growth_logs')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_sender_created')
        batch_op.drop_index('ix_messages_conversation_sequence')

    op.drop_table('messages')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index('ix_devices_account')

    op.drop_table('devices')
    with op.batch_alter_table('conversation_members', schema=None) as batch_op:
        batch_op.drop_index('ix_conversation_members_account')

    op.drop_table('conversation_members')
    with op.batch_alter_table('caregiver_invitations', schema=None) as batch_op:
        batch_op.drop_index('ix_caregiver_invites_recipient')
        batch_op.drop_index('ix_caregiver_invites_pet')

    op.drop_table('caregiver_invitations')
    op.drop_table('account_web_preferences')
    op.drop_table('account_pet_relations')
    with op.batch_alter_table('reminder_occurrences', schema=None) as batch_op:
        batch_op.drop_index('ix_reminder_occurrences_updated')
        batch_op.drop_index('ix_reminder_occurrences_due')

    op.drop_table('reminder_occurrences')
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_index('ix_pets_owner')

    op.drop_table('pets')
    with op.batch_alter_table('pet_templates', schema=None) as batch_op:
        batch_op.drop_index('ix_pet_templates_status')

    op.drop_table('pet_templates')
    with op.batch_alter_table('pet_asset_rights', schema=None) as batch_op:
        batch_op.drop_index('ix_pet_asset_rights_status')
        batch_op.drop_index('ix_pet_asset_rights_artifact')

    op.drop_table('pet_asset_rights')
    with op.batch_alter_table('friendships', schema=None) as batch_op:
        batch_op.drop_index('ix_friendships_low')
        batch_op.drop_index('ix_friendships_high')

    op.drop_table('friendships')
    with op.batch_alter_table('friend_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_friend_requests_sender_status')
        batch_op.drop_index('ix_friend_requests_recipient_status')

    op.drop_table('friend_requests')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_conversations_updated')

    op.drop_table('conversations')
    with op.batch_alter_table('admin_audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_admin_audit_resource')

    op.drop_table('admin_audit_logs')
    with op.batch_alter_table('account_blocks', schema=None) as batch_op:
        batch_op.drop_index('ix_account_blocks_blocked')

    op.drop_table('account_blocks')
    with op.batch_alter_table('pet_visual_identities', schema=None) as batch_op:
        batch_op.drop_index('ix_pet_visual_identities_template')

    op.drop_table('pet_visual_identities')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_username'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
